import datetime

today = datetime.datetime.now()

filename_prefix = today.strftime("%m-%d-%Y")

new_leaflet_filename = f"{filename_prefix}-leaflet.html"

leaflet_html = open(new_leaflet_filename, "x")

template = open("")

for delimiter in leaflet_html(leaflet.replace())


# new_links = open("link-list.html", "r")

# template = open("leaflet.html", "r")

NVP_00000000 = {
    'preheader': 'trees are growing',
    'article-1__link': 'https://caseytrees.org/',
    'article-1__image': 'https://caseytrees.org/wp-content/uploads/2020/03/Cherry-March-Madness-Bracket_Leaflet-Preview-2.png',
    'article-1__heading': 'This is the Article 1 Heading',
    'article-1__description': 'This is the Article 1 Description',
    'article-2__link': 'https://caseytrees.org/',
    'article-2__image': 'https://caseytrees.org/wp-content/uploads/2020/03/Cherry-March-Madness-Bracket_Leaflet-Preview-2.png',
    'article-2__heading': 'This is the Article 2 Heading',
    'article-2__description': 'This is the Article 2 Description',
    'article-3__link': 'https://caseytrees.org/',
    'article-3__image': 'https://caseytrees.org/wp-content/uploads/2020/03/Cherry-March-Madness-Bracket_Leaflet-Preview-2.png',
    'article-3__heading': 'This is the Article 3 Heading',
    'article-3__description': 'This is the Article 3 Description'
}

NVP_20200427 = {
    'preheader': 'Because there is always something more to learn about trees.',
    'article-1__link': 'https://caseytrees.org/2020/04/message-from-mark/?utm_source=leaflet&utm_medium=email&utm_campaign=blog',
    'article-1__alt-text': 'a message from executive director, mark buscaino',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/04/perceptions-browser.jpg',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/04/perceptions-responsive.jpg',
    'article-1__heading': 'A Note From Casey Trees Executive Director, Mark Buscaino',
    'article-1__description': 'While times are challenging, the energy and ideas of Casey Trees and our city remain as creative and strong as ever.',
    'button-1__link': 'https://caseytreesdc.github.io/treereportcard2019/?utm_source=leaflet&utm_medium=email&utm_campaign=trc',
    'button-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/04/Leaflet-button-1-browser.png',
    'button-1__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/04/Leaflet-button-1-responsive.png',
    'button-1__alt-text': 'the 2019 Tree Report Card!',
    'button-2__link': 'https://caseytreesdc.github.io/treereportcard2019/?utm_source=leaflet&utm_medium=email&utm_campaign=trc#navmetrics',
    'button-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/04/Leaflet-button-2-browser.png',
    'button-2__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/04/Leaflet-button-2-responsive.png',
    'button-2__alt-text': 'Check out our grades!',
    'article-2__link': 'https://caseytrees.org/2020/04/weve-added-to-our-virtual-class-offerings/?utm_source=leaflet&utm_medium=email&utm_campaign=edu',
    'article-2__alt-text': 'We’ve Added to Our Virtual Class Offerings!',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/04/leaflet-treeID-browser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/04/leaflet-treeID-resplonsive.png',
    'article-2__heading': 'We’ve Added to Our Virtual Class Offerings!',
    'article-2__description': 'In less than a half hour learn tree tips, tricks, tidbits from the comfort and safety from your own home',
    'article-3__link': 'https://caseytrees.org/2020/04/the-best-thing-to-do-for-urban-trees-this-summer/?utm_source=leaflet&utm_medium=email&utm_campaign=wateringalert',
    'article-3__alt-text': "watering guide",
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/04/water-browser.jpg',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/04/water-resplonsive.jpg',
    'article-3__heading': 'The Best Thing To Do For Urban Trees This Summer',
    'article-3__description': 'So simple, so effective, and yet still so needed',
    'banner__link': 'https://connect.clickandpledge.com/w/Form/76e310e2-e233-46b8-9cf6-c6995b4c5d97?trk=arbordayquiz',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/04/Leaflet-ad.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/04/Leaflet-ad-mobile.png',
    'banner__alt-text': 'Plant it Forward',
}

NVP_20200518 = {
    'preheader': 'Plus, how trees can help us remember those we’ve lost and a mini wellness retreat to close out #MentalHealthAwarenessMonth.',
    'article-1__link': 'https://caseytrees.org/2020/05/stayathome-mini-wellness-and-nature-retreat?utm_source=leaflet&utm_medium=email&utm_campaign=random',
    'article-1__alt-text': 'Mindfulness, trees, and wellness',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/mindfulness-browser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/05/mindfulness-email.png',
    'article-1__heading': '#StayatHome Mini-Wellness and Nature Retreat',
    'article-1__description': 'Close out Mental Health Awareness Month with some quick and restorative practices courtesy of our Youth Programs Coordinator and Certified Yoga Instructor Kelsey',
    'watering__link': 'https://caseytrees.org/take-action/water/?utm_source=leaflet&utm_medium=email&utm_campaign=wateringalert',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater-responsive.png',
    'watering__alt-text': 'Young trees need plenty of water this week.',
    'article-2__link': 'https://caseytrees.org/2020/05/remembering-those-weve-lost-on-memorial-day?utm_source=leaflet&utm_medium=email&utm_campaign=nationalholiday',
    'article-2__alt-text': 'A day of remembrance',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/memorial-bowser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/05/memorial-responlsive.png',
    'article-2__heading': 'Remembering Those We’ve Lost on Memorial Day',
    'article-2__description': "A perennial part of the landscape, trees provide a lush, growing, live memorial to honor special folks",
    'article-3__link': 'https://caseytrees.org/2020/05/remembering-those-weve-lost-on-memorial-day?utm_source=leaflet&utm_medium=email&utm_campaign=nationalholiday',
    'article-3__alt-text': 'A day of remembrance',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/memorial-bowser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/05/memorial-responlsive.png',
    'article-3__heading': 'YCYT Final Episode',
    'article-3__description': 'Make sure the deecription takes up all this space at least.',
    'banner__link': 'https://www.tfaforms.com/4826832',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/leaflet-youth-programs-2020.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/leaflet-youth-programs-2020.png',
    'banner__alt-text': 'youth programs survey',
}

NVP_20200622 = {
    'preheader': 'and we’re getting to the ~root~ of it',
    'article-1__link': 'https://caseytrees.org/2020/06/red-white-and-blue-trees-for-independence-day/?utm_source=leaflet&utm_medium=email&utm_campaign=blog',
    'article-1__alt-text': 'red trees, blue berries, white blossoms!',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/06/redwhiteblue-email-1.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/06/redwhiteblue-email.png',
    'article-1__heading': 'Red, White, and Blue Trees for Independence Day',
    'article-1__description': 'Step away from the face paint and step into the soil.',
    'watering__link': 'https://caseytrees.org/take-action/water/?utm_source=leaflet&utm_medium=email&utm_campaign=wateringalert',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater-responsive.png',
    'watering__alt-text': 'Young trees need plenty of water this week.',
    'article-2__link': 'https://caseytrees.org/2020/06/the-roots-of-the-matter-historical-content-of-urban-environmental-disparities/?utm_source=leaflet&utm_medium=email&utm_campaign=programming',
    'article-2__alt-text': 'we will do our research, and we will envigorate our efforts',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/06/microsite-email-2.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/06/microsite-email.png',
    'article-2__heading': "The Roots of the Matter: Historical Content of Urban Environmental Disparities",
    'article-2__description': "We’re taking a deeper look at historical data to learn how and why environmental inequalities exist in D.C. to inform how we move forward and address them.",
    'article-3__link': 'https://caseytrees.org/2020/06/feelin-shady-trees-to-help-you-beat-the-heat/?utm_source=leaflet&utm_medium=email&utm_campaign=rsh',
    'article-3__alt-text': 'beat the heat under our urban canopy!',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/06/large-canopy-email.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/06/large-canopy-email-3.png',
    'article-3__heading': 'Feelin’ Shady: Trees to Help You Beat the Heat',
    'article-3__description': "Which DMV Tree are you most like?",
    'banner__link': 'https://www.tfaforms.com/4826832',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/leaflet-youth-programs-2020.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/leaflet-youth-programs-2020.png',
    'banner__alt-text': 'youth programs survey',
}

'preheader': 'and a summer Casey Trees update',
    'article-1__link': 'https://caseytrees.org/2020/07/check-out-our-new-trees-near-me-map/?utm_source=leaflet&utm_medium=email&utm_campaign=maps',
    'article-1__alt-text': 'our new "trees by me" map',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/treesnearme-browser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/06/treesnearme-email.png',
    'article-1__heading': 'Check Out Our New Trees Near Me Map',
    'article-1__description': 'It’s pretty self explanatory, but we’ve never featured this many trees on one map.',
    'watering__link': 'https://caseytrees.org/take-action/water/?utm_source=leaflet&utm_medium=email&utm_campaign=wateringalert',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater-responsive.png',
    'watering__alt-text': 'Young trees need plenty of water this week.',
    'article-2__link': 'https://caseytrees.org/2020/07/which-dmv-state-tree-are-you/?utm_source=leaflet&utm_medium=email&utm_campaign=residential',
    'article-2__alt-text': 'what dmv state tree are you?',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/statetreequiz-browser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/06/statetreequiz-email.png',
    'article-2__heading': 'Which DMV State Tree are You?',
    'article-2__description': "Take our quiz to find out if you're more of a flowering dogwood, scarlet oak or white oak.",
    'article-3__link': 'https://caseytrees.org/2020/07/volunteer-event-update-for-the-summer/?utm_source=leaflet&utm_medium=email&utm_campaign=residential',
    'article-3__alt-text': 'volunteer events update summer 2020',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/summerupdate-brwoser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/07/summerupdate-email.png',
    'article-3__heading': 'Volunteer Event Update for the Summer',
    'article-3__description': " Not what we want to say, but what it’s safe to say,",
    'banner__link': 'https://www.tfaforms.com/4826832',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/leaflet-youth-programs-2020.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/leaflet-youth-programs-2020.png',
    'banner__alt-text': 'youth programs survey',
    }

NVP_20200727 = {
    'preheader': 'and trees that are the only host for butterflies 🦋',
    'article-1__link': 'https://caseytrees.org/2020/07/butterflies-and-a-bird-and-their-host-trees/?utm_source=leaflet&utm_medium=email&utm_campaign=blog',
    'article-1__alt-text': 'a cedar waxwing wing perched on a cedar branch',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/butter-birds-email-brwoser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/07/butter-birds-email.png',
    'article-1__heading': 'Butterflies (and a Bird) and their Host Trees',
    'article-1__description': 'Coming soon to a Memorial Park near you - Casey Tree Farm cherries!',
    'watering__link': 'https://caseytrees.org/take-action/water/?utm_source=leaflet&utm_medium=email&utm_campaign=wateringalert',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater-responsive.png',
    'watering__alt-text': 'Young trees need plenty of water this week, despite the rain!.',
    'article-2__link': 'https://caseytrees.org/2020/07/which-tree-wood-make-the-best-bat/?utm_source=leaflet&utm_medium=email&utm_campaign=random',
    'article-2__alt-text': 'Nationals Staium at Dusk',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/nats2020-email-broswer.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/07/nats2020-email.png',
    'article-2__heading': 'Which Tree Wood Make the Best Bat?',
    'article-2__description': ' In honor of Nats Opening Day last week, check out what trees make MLB bats!',
    'article-3__link': 'https://caseytrees.org/2020/07/which-is-which-dogwood-edition/?utm_source=leaflet&utm_medium=email&utm_campaign=mediamention',
    'article-3__alt-text': 'pink and white dogwoods',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/dogwood-leaflet-email-browser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/07/dogwood-leaflet-email-responsive.png',
    'article-3__heading': 'Which is Which: Dogwood Edition',
    'article-3__description': 'Tips on how to differentiate between trees at the species level!',
    'banner__link': 'https://caseytrees.org/farm',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/Leaflet-ad_farm.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/07/Leaflet-ad_farm-responsive.png',
    'banner__alt-text': 'curious about our tree farm?',
}

NVP_20200803 = {
    'preheader': 'and how the “streatery” phenomenon is good for trees and greenspace',
    'article-1__link': 'https://caseytrees.org/2020/08/tree-sources-for-schoolkids/?utm_source=leaflet&utm_medium=email&utm_campaign=store',
    'article-1__alt-text': '',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/junior_urban_forestor_guide-browser.jpg',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/junior_urban_forestor_guide-responsive.jpg',
    'article-1__heading': 'Tree-sources for School Kids',
    'article-1__description': 'Our Junior Urban Forester booklets, usually only available through our summer camp programs, are now for sale!',
    'watering__link': 'https://caseytrees.org/take-action/water/?utm_source=leaflet&utm_medium=email&utm_campaign=wateringalert',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_dontwater.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/WWA_dontwater-responsive.png',
    'watering__alt-text': 'We have finally had rain and we will have some more this week! No need to water this week.',
    'article-2__link': 'https://caseytrees.org/2020/08/streateries/?utm_source=leaflet&utm_medium=email&utm_campaign=advocacy',
    'article-2__alt-text': 'streaeries in adams morgan',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/streateries-browser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/streateries-email.png',
    'article-2__heading': 'What are Streateries and Why They’re Good for Urban Trees and Greenspace',
    'article-2__description': 'What the push outside by businesses and people means for District greenspace - and what you can do about it.',
    'article-3__link': 'https://caseytrees.org/2020/08/which-is-which-magnolia-edition/?utm_source=leaflet&utm_medium=email&utm_campaign=residential',
    'article-3__alt-text': '',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/magnolia-species-browser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/magnolia-species-email.png',
    'article-3__heading': 'Which is Which: Magnolia Edition',
    'article-3__description': 'How to tell between the Souther, Saucer, Star, Sweetbay, or Loebner magnolias.',
    'banner__link': 'https://caseytrees.org/farm',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/Leaflet-ad_farm.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/07/Leaflet-ad_farm-responsive.png',
    'banner__alt-text': 'curious about our tree farm?',
}