import datetime

today = datetime.datetime.now()

filename_prefix = today.strftime("%m-%d-%Y")

new_leaflet_filename = f"{filename_prefix}-leaflet.html"

leaflet_html = open(new_leaflet_filename, "x")

template = open("")

for delimiter in leaflet_html(leaflet.replace())


# new_links = open("link-list.html", "r")

# template = open("leaflet.html", "r")

NVP_00000000 = {
    'preheader': 'trees are growing',
    'article-1__link': 'https://caseytrees.org/',
    'article-1__image': 'https://caseytrees.org/wp-content/uploads/2020/03/Cherry-March-Madness-Bracket_Leaflet-Preview-2.png',
    'article-1__heading': 'This is the Article 1 Heading',
    'article-1__description': 'This is the Article 1 Description',
    'article-2__link': 'https://caseytrees.org/',
    'article-2__image': 'https://caseytrees.org/wp-content/uploads/2020/03/Cherry-March-Madness-Bracket_Leaflet-Preview-2.png',
    'article-2__heading': 'This is the Article 2 Heading',
    'article-2__description': 'This is the Article 2 Description',
    'article-3__link': 'https://caseytrees.org/',
    'article-3__image': 'https://caseytrees.org/wp-content/uploads/2020/03/Cherry-March-Madness-Bracket_Leaflet-Preview-2.png',
    'article-3__heading': 'This is the Article 3 Heading',
    'article-3__description': 'This is the Article 3 Description'
}

NVP_20200427 = {
    'preheader': 'Because there is always something more to learn about trees.',
    'article-1__link': 'https://caseytrees.org/2020/04/message-from-mark/?utm_source=leaflet&utm_medium=email&utm_campaign=blog',
    'article-1__alt-text': 'a message from executive director, mark buscaino',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/04/perceptions-browser.jpg',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/04/perceptions-responsive.jpg',
    'article-1__heading': 'A Note From Casey Trees Executive Director, Mark Buscaino',
    'article-1__description': 'While times are challenging, the energy and ideas of Casey Trees and our city remain as creative and strong as ever.',
    'button-1__link': 'https://caseytreesdc.github.io/treereportcard2019/?utm_source=leaflet&utm_medium=email&utm_campaign=trc',
    'button-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/04/Leaflet-button-1-browser.png',
    'button-1__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/04/Leaflet-button-1-responsive.png',
    'button-1__alt-text': 'the 2019 Tree Report Card!',
    'button-2__link': 'https://caseytreesdc.github.io/treereportcard2019/?utm_source=leaflet&utm_medium=email&utm_campaign=trc#navmetrics',
    'button-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/04/Leaflet-button-2-browser.png',
    'button-2__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/04/Leaflet-button-2-responsive.png',
    'button-2__alt-text': 'Check out our grades!',
    'article-2__link': 'https://caseytrees.org/2020/04/weve-added-to-our-virtual-class-offerings/?utm_source=leaflet&utm_medium=email&utm_campaign=edu',
    'article-2__alt-text': 'We’ve Added to Our Virtual Class Offerings!',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/04/leaflet-treeID-browser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/04/leaflet-treeID-resplonsive.png',
    'article-2__heading': 'We’ve Added to Our Virtual Class Offerings!',
    'article-2__description': 'In less than a half hour learn tree tips, tricks, tidbits from the comfort and safety from your own home',
    'article-3__link': 'https://caseytrees.org/2020/04/the-best-thing-to-do-for-urban-trees-this-summer/?utm_source=leaflet&utm_medium=email&utm_campaign=wateringalert',
    'article-3__alt-text': "watering guide",
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/04/water-browser.jpg',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/04/water-resplonsive.jpg',
    'article-3__heading': 'The Best Thing To Do For Urban Trees This Summer',
    'article-3__description': 'So simple, so effective, and yet still so needed',
    'banner__link': 'https://connect.clickandpledge.com/w/Form/76e310e2-e233-46b8-9cf6-c6995b4c5d97?trk=arbordayquiz',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/04/Leaflet-ad.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/04/Leaflet-ad-mobile.png',
    'banner__alt-text': 'Plant it Forward',
}

NVP_20200518 = {
    'preheader': 'Plus, how trees can help us remember those we’ve lost and a mini wellness retreat to close out #MentalHealthAwarenessMonth.',
    'article-1__link': 'https://caseytrees.org/2020/05/stayathome-mini-wellness-and-nature-retreat?utm_source=leaflet&utm_medium=email&utm_campaign=random',
    'article-1__alt-text': 'Mindfulness, trees, and wellness',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/mindfulness-browser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/05/mindfulness-email.png',
    'article-1__heading': '#StayatHome Mini-Wellness and Nature Retreat',
    'article-1__description': 'Close out Mental Health Awareness Month with some quick and restorative practices courtesy of our Youth Programs Coordinator and Certified Yoga Instructor Kelsey',
    'watering__link': 'https://caseytrees.org/take-action/water/?utm_source=leaflet&utm_medium=email&utm_campaign=wateringalert',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater-responsive.png',
    'watering__alt-text': 'Young trees need plenty of water this week.',
    'article-2__link': 'https://caseytrees.org/2020/05/remembering-those-weve-lost-on-memorial-day?utm_source=leaflet&utm_medium=email&utm_campaign=nationalholiday',
    'article-2__alt-text': 'A day of remembrance',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/memorial-bowser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/05/memorial-responlsive.png',
    'article-2__heading': 'Remembering Those We’ve Lost on Memorial Day',
    'article-2__description': "A perennial part of the landscape, trees provide a lush, growing, live memorial to honor special folks",
    'article-3__link': 'https://caseytrees.org/2020/05/remembering-those-weve-lost-on-memorial-day?utm_source=leaflet&utm_medium=email&utm_campaign=nationalholiday',
    'article-3__alt-text': 'A day of remembrance',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/memorial-bowser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/05/memorial-responlsive.png',
    'article-3__heading': 'YCYT Final Episode',
    'article-3__description': 'Make sure the deecription takes up all this space at least.',
    'banner__link': 'https://www.tfaforms.com/4826832',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/leaflet-youth-programs-2020.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/leaflet-youth-programs-2020.png',
    'banner__alt-text': 'youth programs survey',
}

NVP_20200622 = {
    'preheader': 'and we’re getting to the ~root~ of it',
    'article-1__link': 'https://caseytrees.org/2020/06/red-white-and-blue-trees-for-independence-day/?utm_source=leaflet&utm_medium=email&utm_campaign=blog',
    'article-1__alt-text': 'red trees, blue berries, white blossoms!',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/06/redwhiteblue-email-1.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/06/redwhiteblue-email.png',
    'article-1__heading': 'Red, White, and Blue Trees for Independence Day',
    'article-1__description': 'Step away from the face paint and step into the soil.',
    'watering__link': 'https://caseytrees.org/take-action/water/?utm_source=leaflet&utm_medium=email&utm_campaign=wateringalert',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater-responsive.png',
    'watering__alt-text': 'Young trees need plenty of water this week.',
    'article-2__link': 'https://caseytrees.org/2020/06/the-roots-of-the-matter-historical-content-of-urban-environmental-disparities/?utm_source=leaflet&utm_medium=email&utm_campaign=programming',
    'article-2__alt-text': 'we will do our research, and we will envigorate our efforts',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/06/microsite-email-2.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/06/microsite-email.png',
    'article-2__heading': "The Roots of the Matter: Historical Content of Urban Environmental Disparities",
    'article-2__description': "We’re taking a deeper look at historical data to learn how and why environmental inequalities exist in D.C. to inform how we move forward and address them.",
    'article-3__link': 'https://caseytrees.org/2020/06/feelin-shady-trees-to-help-you-beat-the-heat/?utm_source=leaflet&utm_medium=email&utm_campaign=rsh',
    'article-3__alt-text': 'beat the heat under our urban canopy!',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/06/large-canopy-email.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/06/large-canopy-email-3.png',
    'article-3__heading': 'Feelin’ Shady: Trees to Help You Beat the Heat',
    'article-3__description': "Which DMV Tree are you most like?",
    'banner__link': 'https://www.tfaforms.com/4826832',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/leaflet-youth-programs-2020.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/leaflet-youth-programs-2020.png',
    'banner__alt-text': 'youth programs survey',
}

'preheader': 'and a summer Casey Trees update',
    'article-1__link': 'https://caseytrees.org/2020/07/check-out-our-new-trees-near-me-map/?utm_source=leaflet&utm_medium=email&utm_campaign=maps',
    'article-1__alt-text': 'our new "trees by me" map',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/treesnearme-browser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/06/treesnearme-email.png',
    'article-1__heading': 'Check Out Our New Trees Near Me Map',
    'article-1__description': 'It’s pretty self explanatory, but we’ve never featured this many trees on one map.',
    'watering__link': 'https://caseytrees.org/take-action/water/?utm_source=leaflet&utm_medium=email&utm_campaign=wateringalert',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater-responsive.png',
    'watering__alt-text': 'Young trees need plenty of water this week.',
    'article-2__link': 'https://caseytrees.org/2020/07/which-dmv-state-tree-are-you/?utm_source=leaflet&utm_medium=email&utm_campaign=residential',
    'article-2__alt-text': 'what dmv state tree are you?',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/statetreequiz-browser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/06/statetreequiz-email.png',
    'article-2__heading': 'Which DMV State Tree are You?',
    'article-2__description': "Take our quiz to find out if you're more of a flowering dogwood, scarlet oak or white oak.",
    'article-3__link': 'https://caseytrees.org/2020/07/volunteer-event-update-for-the-summer/?utm_source=leaflet&utm_medium=email&utm_campaign=residential',
    'article-3__alt-text': 'volunteer events update summer 2020',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/summerupdate-brwoser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/07/summerupdate-email.png',
    'article-3__heading': 'Volunteer Event Update for the Summer',
    'article-3__description': " Not what we want to say, but what it’s safe to say,",
    'banner__link': 'https://www.tfaforms.com/4826832',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/leaflet-youth-programs-2020.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/leaflet-youth-programs-2020.png',
    'banner__alt-text': 'youth programs survey',
    }

NVP_20200727 = {
    'preheader': 'and trees that are the only host for butterflies 🦋',
    'article-1__link': 'https://caseytrees.org/2020/07/butterflies-and-a-bird-and-their-host-trees/?utm_source=leaflet&utm_medium=email&utm_campaign=blog',
    'article-1__alt-text': 'a cedar waxwing wing perched on a cedar branch',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/butter-birds-email-brwoser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/07/butter-birds-email.png',
    'article-1__heading': 'Butterflies (and a Bird) and their Host Trees',
    'article-1__description': 'Coming soon to a Memorial Park near you - Casey Tree Farm cherries!',
    'watering__link': 'https://caseytrees.org/take-action/water/?utm_source=leaflet&utm_medium=email&utm_campaign=wateringalert',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater-responsive.png',
    'watering__alt-text': 'Young trees need plenty of water this week, despite the rain!.',
    'article-2__link': 'https://caseytrees.org/2020/07/which-tree-wood-make-the-best-bat/?utm_source=leaflet&utm_medium=email&utm_campaign=random',
    'article-2__alt-text': 'Nationals Staium at Dusk',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/nats2020-email-broswer.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/07/nats2020-email.png',
    'article-2__heading': 'Which Tree Wood Make the Best Bat?',
    'article-2__description': ' In honor of Nats Opening Day last week, check out what trees make MLB bats!',
    'article-3__link': 'https://caseytrees.org/2020/07/which-is-which-dogwood-edition/?utm_source=leaflet&utm_medium=email&utm_campaign=mediamention',
    'article-3__alt-text': 'pink and white dogwoods',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/dogwood-leaflet-email-browser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/07/dogwood-leaflet-email-responsive.png',
    'article-3__heading': 'Which is Which: Dogwood Edition',
    'article-3__description': 'Tips on how to differentiate between trees at the species level!',
    'banner__link': 'https://caseytrees.org/farm',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/Leaflet-ad_farm.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/07/Leaflet-ad_farm-responsive.png',
    'banner__alt-text': 'curious about our tree farm?',
}

NVP_20200803 = {
    'preheader': 'and how the “streatery” phenomenon is good for trees and greenspace',
    'article-1__link': 'https://caseytrees.org/2020/08/tree-sources-for-schoolkids/?utm_source=leaflet&utm_medium=email&utm_campaign=store',
    'article-1__alt-text': '',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/junior_urban_forestor_guide-browser.jpg',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/junior_urban_forestor_guide-responsive.jpg',
    'article-1__heading': 'Tree-sources for School Kids',
    'article-1__description': 'Our Junior Urban Forester booklets, usually only available through our summer camp programs, are now for sale!',
    'watering__link': 'https://caseytrees.org/take-action/water/?utm_source=leaflet&utm_medium=email&utm_campaign=wateringalert',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_dontwater.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/WWA_dontwater-responsive.png',
    'watering__alt-text': 'We have finally had rain and we will have some more this week! No need to water this week.',
    'article-2__link': 'https://caseytrees.org/2020/08/streateries/?utm_source=leaflet&utm_medium=email&utm_campaign=advocacy',
    'article-2__alt-text': 'streaeries in adams morgan',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/streateries-browser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/streateries-email.png',
    'article-2__heading': 'What are Streateries and Why They’re Good for Urban Trees and Greenspace',
    'article-2__description': 'What the push outside by businesses and people means for District greenspace - and what you can do about it.',
    'article-3__link': 'https://caseytrees.org/2020/08/which-is-which-magnolia-edition/?utm_source=leaflet&utm_medium=email&utm_campaign=residential',
    'article-3__alt-text': '',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/magnolia-species-browser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/magnolia-species-email.png',
    'article-3__heading': 'Which is Which: Magnolia Edition',
    'article-3__description': 'How to tell between the Souther, Saucer, Star, Sweetbay, or Loebner magnolias.',
    'banner__link': 'https://caseytrees.org/farm',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/Leaflet-ad_farm.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/07/Leaflet-ad_farm-responsive.png',
    'banner__alt-text': 'curious about our tree farm?',
}


NVP_20200803 = {
    'preheader': 'and how the “streatery” phenomenon is good for trees and greenspace',
    'article-1__link': 'https://caseytrees.org/2020/08/tree-sources-for-schoolkids/?utm_source=leaflet&utm_medium=email&utm_campaign=store',
    'article-1__alt-text': '',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/junior_urban_forestor_guide-browser.jpg',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/junior_urban_forestor_guide-responsive.jpg',
    'article-1__heading': 'Tree-sources for School Kids',
    'article-1__description': 'Our Junior Urban Forester booklets, usually only available through our summer camp programs, are now for sale!',
    'watering__link': 'https://caseytrees.org/take-action/water/?utm_source=leaflet&utm_medium=email&utm_campaign=wateringalert',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_dontwater.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/WWA_dontwater-responsive.png',
    'watering__alt-text': 'We have finally had rain and we will have some more this week! No need to water this week.',
    'article-2__link': 'https://caseytrees.org/2020/08/streateries/?utm_source=leaflet&utm_medium=email&utm_campaign=advocacy',
    'article-2__alt-text': 'streaeries in adams morgan',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/streateries-browser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/streateries-email.png',
    'article-2__heading': 'What are Streateries and Why They’re Good for Urban Trees and Greenspace',
    'article-2__description': 'What the push outside by businesses and people means for District greenspace - and what you can do about it.',
    'article-3__link': 'https://caseytrees.org/2020/08/which-is-which-magnolia-edition/?utm_source=leaflet&utm_medium=email&utm_campaign=residential',
    'article-3__alt-text': '',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/magnolia-species-browser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/magnolia-species-email.png',
    'article-3__heading': 'Which is Which: Magnolia Edition',
    'article-3__description': 'How to tell between the Southern, Saucer, Star, Sweetbay, or Loebner magnolias.',
    'banner__link': 'https://caseytrees.org/farm',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/Leaflet-ad_farm.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/07/Leaflet-ad_farm-responsive.png',
    'banner__alt-text': 'curious about our tree farm?',
}

NVP_20200803 = {
    'preheader': 'and August is Tree Check Month!',
    'article-1__link': 'https://caseytrees.org/2020/08/keep-your-drinks-and-dcs-trees-cool-with-our-custom-yetis/?utm_source=leaflet&utm_medium=email&utm_campaign=store',
    'article-1__alt-text': 'the casey trees x yeti with a pitcher of lemonade!',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/yeti-browser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/yeti-email.png',
    'article-1__heading': 'Keep Your Drinks (and DC’s Trees!) Cool with Our Custom Yetis',
    'article-1__description': 'Another tree-riffic addition to our store.',
    'watering__link': 'https://caseytrees.org/take-action/water/?utm_source=leaflet&utm_medium=email&utm_campaign=wateringalert',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater-responsive.png',
    'watering__alt-text': 'Even with the bit of rain, trees need more water this week.',
    'article-2__link': 'https://caseytrees.org/2020/08/garden-centers-and-nurseries-of-the-dmv/?utm_source=leaflet&utm_medium=email&utm_campaign=caseytreefarm',
    'article-2__alt-text': 'blues skies at the farm',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/farm-rebate-browser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/farm-rebate-email.png',
    'article-2__heading': 'Our Favorite Tree Nursery in the DMV',
    'article-2__description': 'and how to get $100 back when you plant a tree.',
    'article-3__link': 'https://caseytrees.org/2020/08/august-is-tree-check-month-2/?utm_source=leaflet&utm_medium=email&utm_campaign=feeforservice',
    'article-3__alt-text': '',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/tree-check-browser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/tree-check-email.png',
    'article-3__heading': 'August is Tree Check Month',
    'article-3__description': 'See something concerning? Our arborists are available!',
    'banner__link': 'https://casey-trees-dc.square.site/product/junior-urban-forester-package/85?cs=true',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/Leaflet-ad_TREEWISE.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/Leaflet-ad_TREEWISE.png',
    'banner__alt-text': 'at-home learning for kids',
}


NVP_20200817 = {
    'preheader': 'We’re celebrating National Dog Day with a complete canine collection of stories!',
    'article-1__link': 'https://caseytrees.org/2020/08/canopy-cover-at-dog-parks-in-dc/',
    'article-1__alt-text': 'a black lab puppy!',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/dogparks-browser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/dogparks-email.png',
    'article-1__heading': 'Executive Statement on Fall Events',
    'article-1__description': 'We have always, and will always, err on the side of caution to ensure your safety and this is no exception.',
    'watering__link': 'https://caseytrees.org/take-action/water/?utm_source=leaflet&utm_medium=email&utm_campaign=wateringalert',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater-responsive.png',
    'watering__alt-text': 'Even with the bit of rain, trees need more water this week.',
    'article-2__link': 'https://caseytrees.org/2020/08/an-update-on-pepcos-green-wall/?utm_source=leaflet&utm_medium=email&utm_campaign=citypartner',
    'article-2__alt-text': '',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/vinewall-update-browser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/vinewall-update-email.png',
    'article-2__heading': 'An Update on PEPCO’s Green Wall',
    'article-2__description': 'Ahh the beauty of consistent maintenance and care (not to mention a satisfying before and after!)',
    'article-3__link': 'https://caseytrees.org/2020/08/catch-us-for-teen-tuesday-exploring-land-use-and-climate-change/?utm_source=leaflet&utm_medium=email&utm_campaign=programming',
    'article-3__alt-text': '',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/teentuesday-browser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/teentuesdayemail.png',
    'article-3__heading': 'Catch Us for Teen Tuesday: Exploring Land Use and Climate Change',
    'article-3__description': 'A tree-source just for teens!',
    'banner__link': 'https://casey-trees-dc.square.site/product/face-mask-dc-flag/87?cs=true',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/Mask_Ad_1.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/MaskAd2-responsive.png',
    'banner__alt-text': 'Get a Casey Trees Mask! Protect Yourself, Protect others, Protect Our Urban Forester',
}


NVP_20200824 = {
    'preheader': 'We’re celebrating National Dog Day with a complete canine collection of stories!',
    'article-1__link': 'https://caseytrees.org/2020/08/canopy-cover-at-dog-parks-in-dc/?utm_source=leaflet&utm_medium=email&utm_campaign=gis',
    'article-1__alt-text': 'a lab puppy!',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/dog-park-browser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/dog-park-email.png',
    'article-1__heading': 'Canopy Cover at Dog Parks in DC',
    'article-1__description': 'Counting down the top 10 puppy play places.',
    'watering__link': 'https://caseytrees.org/take-action/water/?utm_source=leaflet&utm_medium=email&utm_campaign=wateringalert',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater-responsive.png',
    'watering__alt-text': 'Even with the bit of rain, trees need more water this week.',
    'article-2__link': 'https://caseytrees.org/2020/08/help-trees-survive-the-dog-days-of-summer/?utm_source=leaflet&utm_medium=email&utm_campaign=treecare',
    'article-2__alt-text': '',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/option-browser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/option-email.png',
    'article-2__heading': 'Help Trees Survive the Dog Days of Summer',
    'article-2__description': 'Tips on how to help trees make it despite prolonged heat, short and intense rainfall and even lawn maintenance equipment.',
    'article-3__link': 'https://caseytrees.org/2020/08/popular-dogs-as-trees-that-we-can-plant-in-your-yard-for-free/?utm_source=leaflet&utm_medium=email&utm_campaign=residential',
    'article-3__alt-text': '',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/breedsastrees-browser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/breedsastrees-email.png',
    'article-3__heading': 'Popular Dogs as Trees (that we can plant in your yard for free!)',
    'article-3__description': 'Which DC tree represents a golden retriever? Or a Corgi?',
    'banner__link': 'https://casey-trees-dc.square.site/product/face-mask-dc-flag/87?cs=true',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/Mask_Ad_1.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/MaskAd2-responsive.png',
    'banner__alt-text': 'Get a Casey Trees Mask! Protect Yourself, Protect others, Protect Our Urban Forester',
}


NVP_20200831 = {
    'preheader': 'A book recommendation, a virtual annual meeting, and more exciting, pandemic friendly activities.',
    'article-1__link': 'https://caseytrees.org/2020/08/mac-isa-2020-annual-meeting/?utm_source=leaflet&utm_medium=email&utm_campaign=citypartner',
    'article-1__alt-text': '',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/MAC-ISA-browser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/MAC-ISA-email.png',
    'article-1__heading': 'MAC-ISA 2020 Annual Meeting ',
    'article-1__description': 'Take advantage of varied and creative programming, CEUs, and networking opportunities during a pandemic.',
    'watering__link': 'https://caseytrees.org/take-action/water/?utm_source=leaflet&utm_medium=email&utm_campaign=wateringalert',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_optional.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_optional-responsive.png',
    'watering__alt-text': 'We had some rain, water if you need, but trees are hydrated!.',
    'article-2__link': 'https://caseytrees.org/2020/08/black-woman-in-green/?utm_source=leaflet&utm_medium=email&utm_campaign=programming',
    'article-2__alt-text': '',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/BWING-browser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/BWING-email.png',
    'article-2__heading': 'Black Woman in Green',
    'article-2__description': 'Marking the passage of the 19th Amendment, while learning more about our own field.',
    'article-3__link': 'https://caseytrees.org/2020/08/a-new-era-on-12th-street-ne/?utm_source=leaflet&utm_medium=email&utm_campaign=random',
    'article-3__alt-text': 'Gloria Brown and the Inmarked Trail to Forest Service LEadership',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/annex-browser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/annex-email.png',
    'article-3__heading': 'A New Era on 12th Street NE',
    'article-3__description': 'Looking back before looking forward.',
    'banner__link': 'https://casey-trees-dc.square.site/product/face-mask-dc-flag/87?cs=true',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/Mask_Ad_1.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/MaskAd2-responsive.png',
    'banner__alt-text': 'Get a Casey Trees Mask! Protect Yourself, Protect others, Protect Our Urban Forester',
}

NVP_20200914 = {
    'preheader': 'Where to find, and how to identify, beloved fall foliage right outside your door!',
    'article-1__link': 'https://caseytrees.org/2020/09/a-frontline-fall-forecast/?utm_source=leaflet&utm_medium=email&utm_campaign=staff',
    'article-1__alt-text': '',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/09/fall-colors-browser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/09/fall-colors-email.png',
    'article-1__heading': 'We Updated our Fall Colors Map',
    'article-1__description': 'With data you can do a lot of things, but we made a Fall Color map to help you make the most of fall foliage without even leaving the city - or your neighborhood!',
    'watering__link': 'https://caseytrees.org/2020/09/we-updated-our-fall-colors-map/?utm_source=leaflet&utm_medium=email&utm_campaign=maps',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater-responsive.png',
    'watering__alt-text': 'We had some rain, but our trees still need water!.',
    'article-2__link': 'https://caseytrees.org/2020/09/tree-dedications-are-still-on-for-fall/?utm_source=leaflet&utm_medium=email&utm_campaign=dedication',
    'article-2__alt-text': '',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/09/member-callout-browsers.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/09/member-callout-email.png',
    'article-2__heading': 'Tree Dedications are Still on for Fall',
    'article-2__description': 'An opportunity for you to plant a tree in honor of a loved one',
    'article-3__link': 'https://caseytrees.org/2020/09/viva-los-arboles/?utm_source=leaflet&utm_medium=email&utm_campaign=nationalholiday',
    'article-3__alt-text': '',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/09/hispanic-heritage-browser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/09/hispanic-heritage-email.png',
    'article-3__heading': 'Viva los Árboles',
    'article-3__description': 'From September 15 to October 15, National Hispanic Heritage Month celebrates the histories, cultures, and contributions of our ancestors from Spain, Mexico, the Caribbean and the Americas',
    'banner__link': 'https://casey-trees-dc.square.site/product/face-mask-dc-flag/87?cs=true',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/Mask_Ad_1.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/MaskAd2-responsive.png',
    'banner__alt-text': 'Get a Casey Trees Mask! Protect Yourself, Protect others, Protect Our Urban Forester',
}

NVP_20200921 = {
    'preheader': 'and celebrate the third oldest National Park this weekend!',
    'article-1__link': 'https://caseytrees.org/2020/09/why-were-celebrating-the-founding-of-the-third-oldest-national-park/?utm_source=leaflet&utm_medium=email&utm_campaign=citypartner',
    'article-1__alt-text': '',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/09/NPLDRCPD-browser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/09/NPLDRCPD-email.png',
    'article-1__heading': 'Celebrating the Founding of the Third Oldest National Park',
    'article-1__description': 'It’s a jam-packed weekend for Rock Creek Park; it’s both National Public Lands Day *and* Rock Creek Park Day!',
    'watering__link': 'https://caseytrees.org/take-action/water/',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater-responsive.png',
    'watering__alt-text': 'We had some rain, but our trees still need water!.',
    'article-2__link': 'https://caseytrees.org/2020/09/pawpaws-have-arrived-how-to-spot-or-find-one-near-you/?utm_source=leaflet&utm_medium=email&utm_campaign=maps',
    'article-2__alt-text': '',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/09/pawpaw-party-browser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/09/pawpaw-party-email.png',
    'article-2__heading': 'Pawpaws Have Arrived. How to Spot One Near You',
    'article-2__description': 'Have you heard of this regional delicacy?',
    'article-3__link': 'https://caseytrees.org/2020/09/connect-with-hispanic-heritage-in-the-us/?utm_source=leaflet&utm_medium=email&utm_campaign=nationalholiday',
    'article-3__alt-text': '',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/09/hispanicheritagemonth-browser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/09/hispanicheritagemonth-email.png',
    'article-3__heading': 'Connect with Hispanic Heritage in the US',
    'article-3__description': 'With local and national events and resources!',
    'banner__link': 'https://www.mac-isa.org/events',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/09/Leaflet-ad_mac-isa-1.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/09/Leaflet-ad_mac-isa-mobile.png',
    'banner__alt-text': 'Register for the MAC-ISA conference',
}


NVP_20200928 = {
    'preheader': 'and Tree ID in the Fall',
    'article-1__link': 'https://caseytrees.org/2020/09/membership/?utm_source=leaflet&utm_medium=email&utm_campaign=membership',
    'article-1__alt-text': 'stickers and the membership guid to the city of trees',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/09/MEMBERSHIP-LEAFLET-01-browser-2.jpg',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/09/MEMBERSHIP-LEAFLET-01-email.jpg',
    'article-1__heading': 'Casey Trees Membership',
    'article-1__description': 'The best time to plant a tree was 20 years ago. The second best time is right now.',
    'watering__link': 'https://caseytrees.org/take-action/water/',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/05/WWA_mustwater-responsive.png',
    'watering__alt-text': 'We had some rain, but our trees still need water!.',
    'article-2__link': 'https://caseytrees.org/2020/09/last-day-to-register-to-earn-ceus-next-week/?utm_source=leaflet&utm_medium=email&utm_campaign=citypartner',
    'article-2__alt-text': '',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/09/MAC-ISA-browser-small.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/08/MAC-ISA-email.png',
    'article-2__heading': 'Last Day to Register to Earn CEUs Next Week',
    'article-2__description': 'at the MAC-ISA 2020 Annual Meeting. ',
    'article-3__link': 'https://caseytrees.org/2020/09/five-fall-trees-to-id-or-plant-for-free/?utm_source=leaflet&utm_medium=email&utm_campaign=riversmarthomes',
    'article-3__alt-text': '',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/09/five-fall-foliage-browser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/09/five-fall-foliage-email.png',
    'article-3__heading': 'Five Fall Trees to ID (OR Plant for Free)',
    'article-3__description': ' Fall foliage is beautiful for the eyes and helpful for tree ID!',
    'banner__link': 'https://www.eventbrite.com/o/casey-trees-12952944328',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/09/Leaflet-ad_tree-walk.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/09/Leaflet-ad_tree-walk-mobile.png',
    'banner__alt-text': 'Register Now: Tree ID Walk',
}


NVP_20201005 = {
    'preheader': 'and happy Oaktober!',
    'article-1__link': 'https://caseytrees.org/2020/10/take-our-dc-parks-challenge/?utm_source=leaflet&utm_medium=email&utm_campaign=citypartner',
    'article-1__alt-text': '',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/ready2play-browser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/09/ready2play-email.png',
    'article-1__heading': 'Take our DC Parks Challenge',
    'article-1__description': 'Help Plan the Future of DC Parks!',
    'watering__link': 'https://caseytrees.maps.arcgis.com/apps/webappviewer/index.html?id=c7c2a30d5c95440b8316b12c7add426d',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/Leaflet-ad_fall-color-map.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/10/Leaflet-ad_fall-color-map-mobile.png',
    'watering__alt-text': 'View our fall color map.',
    'article-2__link': 'https://caseytrees.org/2020/10/feelin-hot-hot-hot-2020-weekly-watering-alert-wrap-up/?utm_source=leaflet&utm_medium=email&utm_campaign=weeklywateringalert',
    'article-2__alt-text': '',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/wwa-wrapup-2020-browser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/09/wwa-wrapup-2020-email.png',
    'article-2__heading': 'Feelin’ Hot, Hot, Hot: 2020 Weekly Watering Alert Wrap Up',
    'article-2__description': 'TL;DR there was so much watering this summer.',
    'article-3__link': 'https://caseytrees.org/2020/10/oaktober-bur-oak/?utm_source=leaflet&utm_medium=email&utm_campaign=riversmarthomes',
    'article-3__alt-text': '',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/bur-oak-browser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/09/bur-oak-email.png',
    'article-3__heading': 'Oaktober: Bur Oak',
    'article-3__description': 'We’re celebrating Oak-tober by highlighting some of the Oak species we can plant for free as part of our residential planting programs.',
    'banner__link': 'https://casey-trees-dc.square.site/product/face-mask-dc-flag/87?cs=true',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/Mask_Ad_1.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/MaskAd2-responsive.png',
    'banner__alt-text': 'Get a Casey Trees Mask! Protect Yourself, Protect others, Protect Our Urban Forester',
}


NVP_20201013 = {
    'preheader': 'and we are the champions!',
    'article-1__link': 'https://caseytrees.org/2020/10/pandemic-planting-progress/?utm_source=leaflet&utm_medium=email&utm_campaign=citypartner',
    'article-1__alt-text': '',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/stocking-browser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/10/stocking-email.png',
    'article-1__heading': 'Pandemic Planting Progress',
    'article-1__description': 'With enhanced safety protocols, citywide tree planting - through the work of the city’s Urban Forestry Division and us here at Casey Trees - is up! But what will it take to get to our canopy goal?',
    'watering__link': 'https://caseytrees.maps.arcgis.com/apps/webappviewer/index.html?id=c7c2a30d5c95440b8316b12c7add426d',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/Leaflet-ad_fall-color-map.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/10/Leaflet-ad_fall-color-map-mobile.png',
    'watering__alt-text': 'View our fall color map.',
    'article-2__link': 'https://caseytrees.org/2020/10/2020-champion-tree-register/?utm_source=leaflet&utm_medium=email&utm_campaign=treeinventory',
    'article-2__alt-text': '',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/nuttall-browser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/10/nuttall-email.png',
    'article-2__heading': '2020 Champion Tree Register',
    'article-2__description': 'And where to find DC’s Champion Tree.',
    'article-3__link': 'https://caseytrees.org/2020/10/oaktober-chestnut-oak/?utm_source=leaflet&utm_medium=email&utm_campaign=riversmarthomes',
    'article-3__alt-text': '',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/chestnuut-browser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/10/chestnuut-email.png',
    'article-3__heading': 'Oaktober: Chestnut Oak',
    'article-3__description': 'We’re celebrating Oaktober by highlighting some of the Oak species we can plant for free as part of our residential planting programs.',
    'banner__link': 'https://caseytrees.org/plant/residential-planting/',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/Leaflet-ad_rsh.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/10/Leaflet-ad_rsh-mobile.png',
    'banner__alt-text': 'Want free trees for your home?',
}

NVP_20201019 = {
    'preheader': 'and Oaktober continues!',
    'article-1__link': 'https://caseytrees.org/2020/10/from-our-urban-forestry-fellowship-to-bartlett-tree-research-lab-an-interview-with-two-fellowship-recipients/?utm_source=leaflet&utm_medium=email&utm_campaign=gca-scholarship',
    'article-1__alt-text': '',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/gca-profile-browser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/10/gca-profile-emal.png',
    'article-1__heading': 'From Our Urban Forestry Fellowship to Bartlett Tree Research Lab: An Interview with Two Fellowship Recipients',
    'article-1__description': '“Urban Forestry is a broad, wide applicable field - don’t count you or your research out for this opportunity.”',
    'watering__link': 'https://caseytrees.org/farm',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/07/Leaflet-ad_farm.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/07/Leaflet-ad_farm-responsive.png',
    'watering__alt-text': 'Curious about our trees farm? Explore DC State Nursery at Casey Tree Farm',
    'article-2__link': 'https://caseytrees.org/2020/10/2020-treewise-the-more-things-change-the-more-they-stay-the-same/?utm_source=leaflet&utm_medium=email&utm_campaign=programming',
    'article-2__alt-text': '',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/kid-one-browser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/10/kid-one-email.png',
    'article-2__heading': '2020 TreeWise: The More Things Change, The More They Stay The Same',
    'article-2__description': 'How our summer youth education program went virtual but remained true to its mission to build the next generation of stewards.',
    'article-3__link': 'https://caseytrees.org/2020/10/oaktober-nuttall-oak/?utm_source=leaflet&utm_medium=email&utm_campaign=riversmarthomes',
    'article-3__alt-text': '',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/nuttall-browser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/10/nuttall-email.png',
    'article-3__heading': 'Oaktober: Nuttall Oak',
    'article-3__description': 'We’re celebrating Oaktober by highlighting some of the Oak species we can plant for free as part of our residential planting programs.',
    'banner__link': 'https://caseytrees.org/plant/residential-planting/',
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/Leaflet-ad_rsh.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/10/Leaflet-ad_rsh-mobile.png',
    'banner__alt-text': 'Want free trees for your home?',
}

NVP_20201026 = {
    'preheader': 'Plus, how trees, kids, and Casey Trees are resilient.',
    'article-1__link': 'https://caseytrees.org/2020/10/elag/?utm_source=leaflet&utm_medium=email&utm_campaign=programming',
    'article-1__alt-text': '',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/elag-browser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/10/elag-email.png',
    'article-1__heading': 'Coming Soon to a Classroom Near You: Casey Trees!',
    'article-1__description': 'More on our work through the Environmental Literacy Advancement Grant also known as ELAG.',
    'watering__link': 'https://casey-trees-dc.square.site/',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/Mask_Ad_1.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/MaskAd2-responsive.png',
    'watering__alt-text': 'Check out the Casey Trees Online Store!',
    'article-2__link': 'https://caseytrees.org/2020/10/unbe-leaf-ably-creative-costumes-for-halloween/?utm_source=leaflet&utm_medium=email&utm_campaign=nationalholiday',
    'article-2__alt-text': '',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/halloween-browser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/10/halloween-email.png',
    'article-2__heading': 'Unbe-leaf-ably Creative Costumes for Halloween',
    'article-2__description': 'Let’s go all in on holiday joy this year shall we?',
    'article-3__link': 'https://caseytrees.org/2020/10/20460/?utm_source=leaflet&utm_medium=email&utm_campaign=riversmarthomes',
    'article-3__alt-text': '',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/overcup-broswer.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/10/overcup-email.png',
    'article-3__heading': 'Oaktober: Overcup Oak',
    'article-3__description': 'We’re celebrating Oaktober by highlighting some of the Oak species we can plant for free as part of our residential planting programs.',
    'banner__link': 'https://connect.clickandpledge.com/w/Form/212c9142-dfbb-4801-8e11-d0f1b5810fc0?utm_source=leaflet&utm_medium=email&utm_campaign=membership&trk=leaflet&_ga=2.73358995.129279305.1601908695-656825217.1588074983',
    'banner_text': 'DONATE TODAY',
    'banner__image-browser': '',
    'banner__image-responsive': '',
    'banner__alt-text': '',
}

NVP_20201026 = {
    'preheader': 'and important changes to DC Leaf Collection',
    'article-1__link': 'https://caseytrees.org/2020/10/elag/?utm_source=leaflet&utm_medium=email&utm_campaign=programming',
    'article-1__alt-text': '',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/elag-browser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/10/elag-email.png',
    'article-1__heading': 'Coming Soon to a Classroom Near You: Casey Trees!',
    'article-1__description': 'More on our work through the Environmental Literacy Advancement Grant also known as ELAG.',
    'watering__link': 'https://casey-trees-dc.square.site/',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/Mask_Ad_1.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/MaskAd2-responsive.png',
    'watering__alt-text': 'Check out the Casey Trees Online Store!',
    'article-2__link': 'https://caseytrees.org/2020/10/unbe-leaf-ably-creative-costumes-for-halloween/?utm_source=leaflet&utm_medium=email&utm_campaign=nationalholiday',
    'article-2__alt-text': '',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/halloween-browser.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/10/halloween-email.png',
    'article-2__heading': 'Unbe-leaf-ably Creative Costumes for Halloween',
    'article-2__description': 'Let’s go all in on holiday joy this year shall we?',
    'article-3__link': 'https://caseytrees.org/2020/10/20460/?utm_source=leaflet&utm_medium=email&utm_campaign=riversmarthomes',
    'article-3__alt-text': '',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/10/overcup-broswer.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/10/overcup-email.png',
    'article-3__heading': 'Oaktober: Overcup Oak',
    'article-3__description': 'We’re celebrating Oaktober by highlighting some of the Oak species we can plant for free as part of our residential planting programs.',
    'banner__link': 'https://connect.clickandpledge.com/w/Form/212c9142-dfbb-4801-8e11-d0f1b5810fc0?utm_source=leaflet&utm_medium=email&utm_campaign=membership&trk=leaflet&_ga=2.73358995.129279305.1601908695-656825217.1588074983',
    'banner_text': 'DONATE TODAY',
    'banner__image-browser': '',
    'banner__image-responsive': '',
    'banner__alt-text': '',
}

NVP_20201109 = {
    'preheader': 'Plus, earn CEUs, and witnesses to history.',
    'article-1__link': 'https://caseytrees.org/2020/11/urban-tree-summit/?utm_source=leaflet&utm_medium=email&utm_campaign=greencitiessummit',
    'article-1__alt-text': '',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/11/urbantreesummit-browser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/10/urbantreesummit-email.png',
    'article-1__heading': 'Urban Tree Summit',
    'article-1__description': 'For the future health and welfare of our urban and suburban trees.',
    'watering__link': 'https://caseytrees.org/2020/11/dont-keep-this-to-yourself-advocacy-starts-with-sharing-or-a-zoom-class-to-make-difference/',
    'watering__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/11/Leaflet-ad_aitd.png',
    'watering__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/11/Leaflet-ad_aitd-mobile.png',
    'watering__alt-text': 'Check out the Casey Trees Online Store!',
    'article-2__link': 'https://caseytrees.org/2020/11/magical-maples/?utm_source=leaflet&utm_medium=email&utm_campaign=riversmarthomes',
    'article-2__alt-text': '',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/11/maples-browser-1.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/10/maples-email.png',
    'article-2__heading': 'Magical Maples',
    'article-2__description': 'True stunners of Autumn.',
    'article-3__link': 'https://caseytrees.org/2020/11/five-witness-trees-for-veterans-day-2/?utm_source=leaflet&utm_medium=email&utm_campaign=nationalholiday',
    'article-3__alt-text': '',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/11/witness-trees-browser.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/11/witness-trees-email.png',
    'article-3__heading': 'Five Witness Trees for Veteran’s Day',
    'article-3__description': 'Witness trees are those considered to have been present, and therefore would have been witness to, at key historical events.',
    'banner__link': 'https://caseytrees.org/education/urban-forestry-fellowship/',
    # banner_text if the delimited is 10-26-2020
    # banner_image if the delimited is 08-10-2020
    'banner_text': 'DONATE TODAY', 
    'banner__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/11/Leaflet-ad_gca.png',
    'banner__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/11/Leaflet-ad_gca-mobile.png',
    'banner__alt-text': 'Register Now for the Urban Foresrty Grant',
}

NVP = NVP_20201109

NVP_20201124 = {
    'preheader': 'show some love for the pandemic’s surprising hero - urban trees!',
    'article-1__link': 'https://caseytrees.org/2020/11/10-things-to-do-for-trees/?utm_source=leaflet&utm_medium=email&utm_campaign=eoy',
    'article-1__alt-text': '',
    'article-1__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/11/10-things-browser.png',
    'article-1__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/11/10-things-email.png',
    'article-1__heading': '10 Things to Do for Trees',
    'article-1__description': 'Show some love for the pandemic’s surprising hero - urban trees!',
    'banner-a__text-1': 'Urban Tree Summit Dec. 2nd',
    'banner-a__text-2': 'REGISTER NOW',
    'banner-a__link': 'https://www.eventbrite.com/e/montgomery-parks-and-casey-trees-tickets-121720670803',
    'banner-a__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/11/Leaflet-ad_summit.png',
    'banner-a__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/11/Leaflet-ad_summit-mobile.png',
    'banner-a__alt-text': '',
    'article-2__link': 'https://caseytrees.org/2020/11/thankful-for-trees-2/?utm_source=leaflet&utm_medium=email&utm_campaign=eoy',
    'article-2__alt-text': '',
    'article-2__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/11/thankful-2020-browser1.png',
    'article-2__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/11/thankful-2020-email.png',
    'article-2__heading': 'Thankful for Trees',
    'article-2__description': 'They’re so much more than a pretty face.',
    'article-3__link': 'https://caseytrees.org/2020/11/which-is-which-sweetgum-edition/?utm_source=leaflet&utm_medium=email&utm_campaign=treerebate',
    'article-3__alt-text': '',
    'article-3__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/11/sweetgum-browser1.png',
    'article-3__image-mobile': 'https://caseytrees.org/wp-content/uploads/2020/11/sweetgum-email.png',
    'article-3__heading': 'Which is Which: Sweetgum Edition',
    'article-3__description': 'How to know if you’ll have a handful of spiky fruits.',
    'banner-b__link': 'https://www.eventbrite.com/e/advocacy-in-the-district-tickets-128900213007',
    'banner-b__text': '', 
    'banner-b__image-browser': 'https://caseytrees.org/wp-content/uploads/2018/02/Tree-Advocates-Gif-4-1.gif',
    'banner-b__image-responsive': 'https://caseytrees.org/wp-content/uploads/2018/02/Tree-Advocates-Gif-4-1.gif',
    'banner-b__alt-text': 'AITD',
}
NVP_20201207 = {
    'preheader': 'and tips on regenerative pruning',
    'article-1__link': 'https://caseytrees.org/2020/12/we-made-it-through-2020-a-gift-guide/?utm_source=leaflet&utm_medium=email&utm_campaign=eoy',
    'article-1__alt-text': '',
    'article-1__image': 'https://caseytrees.org/wp-content/uploads/2020/12/gift-guide_leaflet-preview-scaled.jpg',
    'article-1__heading': 'We Made It Through 2020: A Gift Guide',
    'article-1__description': 'What a year folks! Let’s treat each other - the simple things are often best',
    'banner-a__text-1': 'MAKE A YEAR-END GIFT',
    'banner-a__text-2': '',
    'banner-a__link': 'https://connect.clickandpledge.com/w/Form/2ab97890-387e-4b10-a454-6ab08350e1b8?utm_source=leaflet&utm_medium=email&utm_campaign=eoy&utm_content=email8&trk=eoy8',
    'banner-a__image-browser': '',
    'banner-a__image-responsive': '',
    'banner-a__alt-text': '',
    'article-2__link': 'https://caseytrees.org/2020/12/from-the-archives-pruning-tips/?utm_source=leaflet&utm_medium=email&utm_campaign=feeforservice',
    'article-2__alt-text': '',
    'article-2__image': 'https://caseytrees.org/wp-content/uploads/2020/12/tree-pruning-email.png',
    'article-2__heading': 'Don’t Panic! Common Tree Issues and How to Treat Them',
    'article-2__description': 'We provide residential tree consultations through our Fee for Service program',
    'article-3__link': 'https://caseytrees.org/2020/12/preserving-the-rich-agricultural-and-cultural-legacy-of-the-casey-tree-farm-2/?utm_source=leaflet&utm_medium=email&utm_campaign=caseytreefarm',
    'article-3__alt-text': '',
    'article-3__image': 'https://caseytrees.org/wp-content/uploads/2020/08/farm-rebate-email.png',
    'article-3__heading': 'Preserving the Rich Agricultural and Cultural Legacy of the Casey Tree Farm',
    'article-3__description': 'How our Farm, located on the banks of the Shenandoah River, cultivates 100 acres of land sustainably. And how you can help!',
    'banner-b__link': 'https://casey-trees-dc.square.site/product/face-mask-dc-outline/88?cs=true?utm_source%3DLeaflet&trk=eoy5&utm_campaign=eoy&utm_content=email5&utm_medium=email',
    'banner-b__text': '', 
    'banner-b__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/Mask_Ad_1.png',
    'banner-b__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/MaskAd2-responsive.png',
    'banner-b__alt-text': 'Protect Others. Protect Yourself. Protect Our Urban Forest. Link to masks on our online store.',
}
NVP_20201207 = {
    'preheader': 'and tips on regenerative pruning',
    'article-1__link': 'https://caseytrees.org/2020/12/we-made-it-through-2020-a-gift-guide/?utm_source=leaflet&utm_medium=email&utm_campaign=eoy',
    'article-1__alt-text': '',
    'article-1__image': 'https://caseytrees.org/wp-content/uploads/2020/12/Gift-Guide-Leaflet-Preview.gif',
    'article-1__heading': 'We Made It Through 2020: A Gift Guide',
    'article-1__description': 'What a year folks! Let’s treat each other - the simple things are often best',
    'banner-a__text-1': 'MAKE A YEAR-END GIFT',
    'banner-a__text-2': '',
    'banner-a__link': 'https://connect.clickandpledge.com/w/Form/2ab97890-387e-4b10-a454-6ab08350e1b8?utm_source=leaflet&utm_medium=email&utm_campaign=eoy&utm_content=email8&trk=eoy5',
    'banner-a__image-browser': '',
    'banner-a__image-responsive': '',
    'banner-a__alt-text': '',
    'article-2__link': 'https://caseytrees.org/2020/12/from-the-archives-pruning-tips/?utm_source=leaflet&utm_medium=email&utm_campaign=feeforservice',
    'article-2__alt-text': '',
    'article-2__image': 'https://caseytrees.org/wp-content/uploads/2020/12/tree-pruning-email.png',
    'article-2__heading': 'From the Archives: Pruning Tips',
    'article-2__description': 'Tips on how to prune trees yourself, or who you call if you don’t',
    'article-3__link': 'https://caseytrees.org/2020/12/preserving-the-rich-agricultural-and-cultural-legacy-of-the-casey-tree-farm-2/?utm_source=leaflet&utm_medium=email&utm_campaign=caseytreefarm',
    'article-3__alt-text': '',
    'article-3__image': 'https://caseytrees.org/wp-content/uploads/2020/08/farm-rebate-email.png',
    'article-3__heading': 'Preserving the Rich Agricultural and Cultural Legacy of the Casey Tree Farm',
    'article-3__description': 'How our Farm, located on the banks of the Shenandoah River, cultivates 100 acres of land sustainably. And how you can help!',
    'banner-b__link': 'https://www.washingtonpost.com/local/dc-ward-8-parks-cleanup/2020/12/05/1d34f078-260f-11eb-8672-c281c7a2c96e_story.html',
    'banner-b__text-1': 'Casey Trees in the Post', 
    'banner-b__text-2': 'A Fight for Forestry Equity', 
    'banner-b__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/Mask_Ad_1.png',
    'banner-b__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/MaskAd2-responsive.png',
    'banner-b__alt-text': 'Protect Others. Protect Yourself. Protect Our Urban Forest. Link to masks on our online store.',
}

NVP = NVP_20201207


NVP_20201207 = {
    'preheader': 'and tips on regenerative pruning',
    'article-1__link': 'https://caseytrees.org/2020/12/we-made-it-through-2020-a-gift-guide/?utm_source=leaflet&utm_medium=email&utm_campaign=eoy',
    'article-1__alt-text': '',
    'article-1__image': 'https://caseytrees.org/wp-content/uploads/2020/12/Gift-Guide-Leaflet-Preview.gif',
    'article-1__heading': 'We Made It Through 2020: A Gift Guide',
    'article-1__description': 'What a year folks! Let’s treat each other - the simple things are often best',
    'banner-a__text-1': 'MAKE A YEAR-END GIFT',
    'banner-a__text-2': '',
    'banner-a__link': 'https://connect.clickandpledge.com/w/Form/2ab97890-387e-4b10-a454-6ab08350e1b8?utm_source=leaflet&utm_medium=email&utm_campaign=eoy&utm_content=email8&trk=eoy5',
    'banner-a__image-browser': '',
    'banner-a__image-responsive': '',
    'banner-a__alt-text': '',
    'article-2__link': 'https://caseytrees.org/2020/12/from-the-archives-pruning-tips/?utm_source=leaflet&utm_medium=email&utm_campaign=feeforservice',
    'article-2__alt-text': '',
    'article-2__image': 'https://caseytrees.org/wp-content/uploads/2020/12/tree-pruning-email.png',
    'article-2__heading': 'From the Archives: Pruning Tips',
    'article-2__description': 'Tips on how to prune trees yourself, or who you call if you don’t',
    'article-3__link': 'https://caseytrees.org/2020/12/preserving-the-rich-agricultural-and-cultural-legacy-of-the-casey-tree-farm-2/?utm_source=leaflet&utm_medium=email&utm_campaign=caseytreefarm',
    'article-3__alt-text': '',
    'article-3__image': 'https://caseytrees.org/wp-content/uploads/2020/08/farm-rebate-email.png',
    'article-3__heading': 'Preserving the Rich Agricultural and Cultural Legacy of the Casey Tree Farm',
    'article-3__description': 'How our Farm, located on the banks of the Shenandoah River, cultivates 100 acres of land sustainably. And how you can help!',
    'banner-b__link': 'https://www.washingtonpost.com/local/dc-ward-8-parks-cleanup/2020/12/05/1d34f078-260f-11eb-8672-c281c7a2c96e_story.html',
    'banner-b__text-1': 'Casey Trees in the Post', 
    'banner-b__text-2': 'A Fight for Forestry Equity', 
    'banner-b__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/Mask_Ad_1.png',
    'banner-b__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/MaskAd2-responsive.png',
    'banner-b__alt-text': 'Protect Others. Protect Yourself. Protect Our Urban Forest. Link to masks on our online store.',
}

NVP = NVP_20201207


NVP_20201207 = {
    'preheader': 'While those 2 million trees are busy, they need all the help they can get. Donate today.',
    'article-1__link': 'https://caseytrees.org/2020/12/weve-got-you-covered-literally/?utm_source=leaflet&utm_medium=email&utm_campaign=eoy',
    'article-1__alt-text': '',
    'article-1__image': 'https://caseytrees.org/wp-content/uploads/2020/12/covered-email.png',
    'article-1__heading': 'We’ve Got You Covered. Literally.',
    'article-1__description': 'A lush canopy means so much more than shade.',
    'banner-a__text-1': 'MAKE A YEAR-END GIFT',
    'banner-a__text-2': '',
    'banner-a__link': 'https://connect.clickandpledge.com/w/Form/2ab97890-387e-4b10-a454-6ab08350e1b8?utm_source=leaflet&utm_medium=email&utm_campaign=eoy&utm_content=email7B&trk=eoy7',
    'banner-a__image-browser': '',
    'banner-a__image-responsive': '',
    'banner-a__alt-text': '',
    'article-2__link': 'https://caseytrees.org/2020/12/tell-the-difference-between-spruce-and-pine-trees-2/?utm_source=leaflet&utm_medium=email&utm_campaign=riversmarthomes',
    'article-2__alt-text': '',
    'article-2__image': 'https://caseytrees.org/wp-content/uploads/2020/11/spruce-pine-email.png',
    'article-2__heading': 'Tell the Difference Between Spruce and Pine Trees',
    'article-2__description': 'Here’s our quick tip to quit the confusion.',
    'article-3__link': 'https://caseytrees.org/2020/12/trees-that-bring-wonder-to-winter/?utm_source=leaflet&utm_medium=email&utm_campaign=riversmarthomes',
    'article-3__alt-text': '',
    'article-3__image': 'https://caseytrees.org/wp-content/uploads/2020/12/winter-interest-email2020.png',
    'article-3__heading': 'Trees that Bring Wonder to Winter',
    'article-3__description': 'Brighten your view, yard, and mood with these trees that bring some much-needed winter interest.',
    'banner-b__link': 'https://casey-trees-dc.square.site/',
    'banner-b__text-1': 'Masks, Tees, Yeti ramblers, Stickers, and more', 
    'banner-b__text-2': 'CASEY TREES ONLINE STORE', 
    'banner-b__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/Mask_Ad_1.png',
    'banner-b__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/MaskAd2-responsive.png',
    'banner-b__alt-text': 'Protect Others. Protect Yourself. Protect Our Urban Forest. Link to masks on our online store.',
}

NVP = NVP_20201207


NVP_20201214 = {
    'preheader': 'While those 2 million trees are busy, they need all the help they can get. Donate today.',
    'article-1__link': 'https://caseytrees.org/2020/12/weve-got-you-covered-literally/?utm_source=leaflet&utm_medium=email&utm_campaign=eoy',
    'article-1__alt-text': '',
    'article-1__image': 'https://caseytrees.org/wp-content/uploads/2020/12/covered-email.png',
    'article-1__heading': 'Almost to our goal - help us secure a Board Member match. Donate now!',
    'article-1__description': 'Today only, your gift is worth double!',
    'banner-a__text-1': 'MAKE A YEAR-END GIFT',
    'banner-a__text-2': '',
    'banner-a__link': 'https://connect.clickandpledge.com/w/Form/2ab97890-387e-4b10-a454-6ab08350e1b8?utm_source=leaflet&utm_medium=email&utm_campaign=eoy&utm_content=email7B&trk=eoy7',
    'banner-a__image-browser': '',
    'banner-a__image-responsive': '',
    'banner-a__alt-text': '',
    'article-2__link': 'https://caseytrees.org/2020/12/tell-the-difference-between-spruce-and-pine-trees-2/?utm_source=leaflet&utm_medium=email&utm_campaign=riversmarthomes',
    'article-2__alt-text': '',
    'article-2__image': 'https://caseytrees.org/wp-content/uploads/2020/12/winter-tree-care-email.png',
    'article-2__heading': ' Giving Urban Trees a Second Life',
    'article-2__description': 'Here’s our quick tip to quit the confusion.',
    'article-3__link': 'https://caseytrees.org/2020/12/trees-that-bring-wonder-to-winter/?utm_source=leaflet&utm_medium=email&utm_campaign=riversmarthomes',
    'article-3__alt-text': '',
    'article-3__image': 'https://caseytrees.org/wp-content/uploads/2020/12/winter-interest-email2020.png',
    'article-3__heading': 'Giving Urban Trees a Second Life',
    'article-3__description': 'When a tree falls in a city, it is meticulously planned and turned into something magical!',
    'banner-b__link': 'https://casey-trees-dc.square.site/',
    'banner-b__text-1': 'Masks, Tees, Yeti ramblers, Stickers, and more', 
    'banner-b__text-2': 'CASEY TREES ONLINE STORE', 
    'banner-b__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/Mask_Ad_1.png',
    'banner-b__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/MaskAd2-responsive.png',
    'banner-b__alt-text': 'Protect Others. Protect Yourself. Protect Our Urban Forest. Link to masks on our online store.',
}

NVP = NVP_20201214

Wrapping up a most unusual year',
    'article-1__link': 'https://caseytrees.org/2020/12/almost-to-our-goal-help-us-secure-a-board-member-match-donate-now/?utm_source=leaflet&utm_medium=email&utm_campaign=eoy',
    'article-1__alt-text': 'TODAY ONLY YOUR GIFT IS MATCHED',
    'article-1__image': 'https://caseytrees.org/wp-content/uploads/2020/12/match-email.png',
    'article-1__heading': 'Almost to our goal - help us secure a Board Member match. Donate now!',
    'article-1__description': 'Today only, your gift is worth double!',
    'banner-a__text-1': 'MAKE A YEAR-END GIFT',
    'banner-a__text-2': '',
    'banner-a__link': 'https://connect.clickandpledge.com/w/Form/2ab97890-387e-4b10-a454-6ab08350e1b8?utm_source=leaflet&utm_medium=email&utm_campaign=eoy&utm_content=email7B&trk=eoy9',
    'banner-a__image-browser': '',
    'banner-a__image-responsive': '',
    'banner-a__alt-text': '',
    'article-2__link': 'https://caseytrees.org/2020/12/your-new-years-resolutions-can-also-help-urban-forests/?utm_source=leaflet&utm_medium=email&utm_campaign=eoy',
    'article-2__alt-text': '',
    'article-2__image': 'https://caseytrees.org/wp-content/uploads/2020/11/2020-resolutions-email.png',
    'article-2__heading': 'Your New Year’s Resolutions Can Also Help Urban Forests',
    'article-2__description': 'Involve trees in your goals to get active, read or get involved',
    'article-3__link': 'https://caseytrees.org/2020/12/giving-urban-trees-a-second-life-2/?utm_source=leaflet&utm_medium=email&utm_campaign=citypartner',
    'article-3__alt-text': '',
    'article-3__image': 'https://caseytrees.org/wp-content/uploads/2020/11/urban-wood-reuse-email.png',
    'article-3__heading': 'Giving Urban Trees a Second Life',
    'article-3__description': 'When a tree falls in a city, it is meticulously planned and turned into something magical!',
    'banner-b__link': 'https://connect.clickandpledge.com/w/Form/2ab97890-387e-4b10-a454-6ab08350e1b8?utm_source=leaflet&utm_medium=email&utm_campaign=eoy&utm_content=email7B&trk=eoy9',
    'banner-b__text-1': 'Casey Trees Board Members Match up to $5000!', 
    'banner-b__text-2': 'TODAY ONLY', 
    'banner-b__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/Mask_Ad_1.png',
    'banner-b__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/MaskAd2-responsive.png',
    'banner-b__alt-text': 'Protect Others. Protect Yourself. Protect Our Urban Forest. Link to masks on our online store.',


NVP_20201214 = {
    'preheader': 'A Few More Days to Make Your Tax-Deductible Donation',
    'article-1__link': 'https://caseytrees.org/2020/12/no-matter-the-circumstances-we-step-up-for-dcs-trees-will-you-step-up-for-us/?utm_source=leaflet&utm_medium=email&utm_campaign=eoy',
    'article-1__alt-text': 'TODAY ONLY YOUR GIFT IS MATCHED',
    'article-1__image': 'https://caseytrees.org/wp-content/uploads/2020/12/step-up-tree-tag-snow-email.png',
    'article-1__heading': 'No matter the circumstances, we step up for DC’s trees. Will you step up for us?',
    'article-1__description': 'There are a few more days to make your tax-deductible donation',
    'banner-a__text-1': 'MAKE A YEAR-END GIFT',
    'banner-a__text-2': '',
    'banner-a__link': 'https://connect.clickandpledge.com/w/Form/2ab97890-387e-4b10-a454-6ab08350e1b8?utm_source=leaflet&utm_medium=email&utm_campaign=eoy&utm_content=email7B&trk=eoy10',
    'banner-a__image-browser': '',
    'banner-a__image-responsive': '',
    'banner-a__alt-text': '',
    'article-2__link': 'https://caseytrees.org/2020/12/one-month-left-to-apply-for-our-7500-fellowship/?utm_source=leaflet&utm_medium=email&utm_campaign=gcascholarship',
    'article-2__alt-text': '',
    'article-2__image': 'https://caseytrees.org/wp-content/uploads/2020/11/gca-reminder-2019-email.png',
    'article-2__heading': 'One Month Left to Apply for Our $7,500 Fellowship',
    'article-2__description': 'Studying urban forestry, environmental studies, horticulture, forestry or related programs? Apply by Jan 31!',
    'article-3__link': 'https://caseytrees.org/2020/12/wrapping-up-a-most-unusual-year/?utm_source=leaflet&utm_medium=email&utm_campaign=programming',
    'article-3__alt-text': '',
    'article-3__image': 'https://caseytrees.org/wp-content/uploads/2020/12/2020-wrap-up-masked-crew-email.png',
    'article-3__heading': 'Wrapping Up a Most Unusual Year',
    'article-3__description': 'Putting 2020 behind us and looking forward',
    'banner-b__link': 'https://connect.clickandpledge.com/w/Form/2ab97890-387e-4b10-a454-6ab08350e1b8?utm_source=leaflet&utm_medium=email&utm_campaign=eoy&utm_content=email7B&trk=eoy10',
    'banner-b__text-1': 'Trees Need Us and We Need You', 
    'banner-b__text-2': 'MAKE A YEAR-END GIFT', 
    'banner-b__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/08/Mask_Ad_1.png',
    'banner-b__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/08/MaskAd2-responsive.png',
    'banner-b__alt-text': '',
}

NVP = NVP_20201214



NVP_20210104 = {
    'preheader': 'We’re also testifying  in front of the Council',
    'article-1__link': 'https://caseytrees.org/2021/01/were-hiring-5/?utm_source=leaflet&utm_medium=email&utm_campaign=jobs',
    'article-1__alt-text': '',
    'article-1__image': 'https://caseytrees.org/wp-content/uploads/2021/01/hiring-2021-email.jpg',
    'article-1__heading': 'We’re hiring!',
    'article-1__description': 'Positions are available in our Tree Planting and Policy & Land Conservation departments, as well as at our Farm.',
    'banner-a__text-1': 'City Partners in the News: the Kojo Nnamdi Show',
    'banner-a__text-2': "Casey Trees' Partners",
    'banner-a__link': 'https://thekojonnamdishow.org/shows/2021-01-05/achieving-tree-equity-in-the-district',
    'banner-a__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/09/Leaflet-ad_we-are-hiring.png',
    'banner-a__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/09/Leaflet-ad_we-are-hiring-mobile.png',
    'banner-a__alt-text': "We're hiring!",
    'article-2__link': 'https://caseytrees.org/2021/01/we-testified-to-protect-public-heritage-trees/?utm_source=leaflet&utm_medium=email&utm_campaign=advocacy',
    'article-2__alt-text': '',
    'article-2__image': 'https://caseytrees.org/wp-content/uploads/2020/12/heritage-trees-email.png',
    'article-2__heading': 'We Testified to Protect Public Heritage Trees',
    'article-2__description': 'How you can help us close legislativative loopholes.',
    'article-3__link': 'https://caseytrees.org/2021/01/to-our-supporters/?utm_source=leaflet&utm_medium=email&utm_campaign=eoy',
    'article-3__alt-text': '',
    'article-3__image': 'https://caseytrees.org/wp-content/uploads/2020/12/eoy-thanks-email.png',
    'article-3__heading': 'To Our Supporters',
    'article-3__description': 'We truly appreciate your generosity, friendship and shared belief that a tree-filled DC is a better place to live, work and play.',
    'banner-b__link': 'https://caseytrees.org/education/urban-forestry-fellowship/',
    'banner-b__text-1': 'Garden Club of America Scholarship', 
    'banner-b__text-2': 'Garden Club of America Scholarship', 
    'banner-b__image-browser': 'https://caseytrees.org/wp-content/uploads/2020/11/Leaflet-ad_gca_v2.png',
    'banner-b__image-responsive': 'https://caseytrees.org/wp-content/uploads/2020/11/Leaflet-ad_gca-mobile-2.png',
    'banner-b__alt-text': 'Urban Forestry Student Scholarship sponsored by the Garden Club of America',
}

